
# import random

# rand_option = random.randint(1,3)


# def game(opt1, opt2):
#     if(opt1 == 1 and opt2 == "s"):
#         print("Draw")
#     elif(opt1 == 2 and opt2 == "s"):
#         print("Player 2 won")
#     elif(opt1 == 2 and opt2 == "w"):
#         print("Draw")
#     elif(opt1 == 1 and opt2 == "w"):
#         print("Computer won")
#     elif(opt1 == 2 and opt2 == "g"):
#         print("Computer won")
#     elif(opt1 == 3 and opt2 == "w"):
#         print("Player 2 won")
#     elif(opt1 == 3 and opt2 == "g"):
#         print("Draw")
#     elif(opt1 == 1 and opt2 == "g"):
#         print("Player 2 won")
#     elif(opt1 == 3 and opt2 == "s"):
#         print("Computer won")
#     else:
#         print("Invalid Keyword")


# a = print(rand_option)
# b = input("Player  - Snake(s), water(w) or gun(g)?")
# game(a, b)






# Importing 'random' Module
import random

# declaraing a function
def gamewin(comp,you):
    # Checking all the possibilities during the game
    if comp==you:
        return None
    elif comp=='s' and you=='w':
        return False
    elif comp=='w' and you=='s':
        return True
    elif comp=='s' and you=='g':
        return True
    elif comp=='g' and you=='s':
        return False
    elif comp=='w' and you=='g':
        return False
    elif comp=='g' and you=='w':
        return True
    

# Assigining values for the random numbers 1 2 and 3 generated by the randint

print("Computer played its turn! Now its your turn")
RandNo=random.randint(1,3)
if RandNo==1:
    comp='s'
if RandNo==2:
    comp='w'
if RandNo==3:
    comp='g'
you=input("Snake(s) water(w) or Gun(g)")
a=gamewin(comp,you)


# Printing if  the game is  won by checking!
if a==None:
    print("Game Tied")
elif a:
    print("Game won")
else:
    print("Game Lost")

     
    
    